name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: build
      run: |
        export GO111MODULE=on
        GOOS=linux go build -o bin/main
        zip bin/release.zip bin/main
    
    - name: Archive artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: bin/release.zip

    - name: Build
      run: GOOS=linux go build -o main .
